version: 2.1

workflows:
  test-deploy:
    jobs:
    - test

jobs:
  test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Run tests
          command: pip env run python manage.py test
